CREATE PROC FI_SP_VerificaBenef
	@CPF VARCHAR(14),
	@IDCLIENTE BIGINT = null,
	@ID BIGINT = null
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT 1 FROM BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE
	ELSE
		SELECT 1 FROM BENEFICIARIOS WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE AND ID != @ID
END